### ISSUE TITLE
The dimension order of swath_data at example 4

### ISSUE THREAD

**Issue by kyang2014** [ajelenak-thg/EC-netCDF-CF#10]
In the example, float swath_data(time,scan,band) should this change to float swath_data(band,time,scan)

since lat and lon are float lat(time,scan) and float lon(time,scan) 
For the convenience of visualization, swath_data(band,time,scan) is easier and efficient to check swath data for each band.

**Comment by ghost** [comment]
I think it comes down to expected data access patterns. Both `swath_data(time, scan, band)` or `swath_data(band, time, scan)` are valid. The former is more appropriate for typical scientific analysis while the latter is, as you've pointed out, better for visualization or any other image processing task that needs quick access to larger area covered by the swath data.

The dimension order in coordinates, like `time`, `lat`, or `lon`, should not ever change as it encodes certain physical properties of the data acquisition process.
