### ISSUE TITLE
Typical values for CF Swath examples

### ISSUE THREAD

**Issue by kyang2014** [ajelenak-thg/EC-netCDF-CF#14]
Need help for typical values  for some CF Swath examples. Details are the following:

(1)	Example 6, band_enum
 band_enum: string band(band_enum) ;
    band:standard_name = "sensor_band_identifier" ;

(2)Example 7and 8, band 
float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "μm" ;

(2)	Example 9, band

band = 1305 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "μm" ;

Also question: Is it possible to have 1305 bands?

(4) Example 9,10, 14:FOR and FOV

 FOR = 45 ; (1)
  FOV = 9 ; (2)

short FOV(FOV); (3)
    FOV:long_name = "Field-of-view ordinal number" ;

**Comment by ghost** [comment]
> (1)	Example 6, band_enum
> band_enum: string band(band_enum) ;
> band:standard_name = "sensor_band_identifier" ;

Let's start with something simple, like: "Ch 1", "Ch 2", "Ch 3", etc.

> (2)Example 7and 8, band
> float band(band) ;
> band:standard_name = "sensor_band_central_radiation_wavelength" ;
> band:units = "μm" ;

Use the values from the _Center Wavelength_ column of the table at https://landsat.gsfc.nasa.gov/preliminary-spectral-response-of-the-operational-land-imager-in-band-band-average-relative-spectral-response/. Also change the `unit` attribute value to `nm`.

> (2)	Example 9, band
> 
> band = 1305 ;
> 
> variables:
> float band(band) ;
> band:standard_name = "sensor_band_central_radiation_wavelength" ;
> band:units = "μm" ;

Use values from this file: 
[airs-bands-central-wavenumber.txt](https://github.com/ajelenak-thg/EC-netCDF-CF/files/880017/airs-bands-central-wavenumber.txt)

You will have to make 2 changes:

1. `standard_name` = `sensor_band_central_radiation_wavenumber`

1. `units` = `cm-1`

> Also question: Is it possible to have 1305 bands?

Yes. The AIRS instrument, for example, has 2378 bands.

> (4) Example 9,10, 14:FOR and FOV
> 
> FOR = 45 ; (1)
> FOV = 9 ; (2)
> 
> short FOV(FOV); (3)
> FOV:long_name = "Field-of-view ordinal number" ;

`FOV` = 1, 2, 3, 4, 5, 6, 7, 8, 9

**Comment by kyang2014** [comment]
I've created netcdf example files based on this ticket.
