### ISSUE TITLE
Comments:  add a paragraph to explain why the values of "coordinates" attributes are different across the examples

### ISSUE THREAD

**Issue by kyang2014** [ajelenak-thg/EC-netCDF-CF#2]
We need to have a paragraph or at least a link to explain how we choose the "coordinates" values for swath variables.
In our example, Some have "lon lat", some have "lon lat band", some have "lon lat band time".
I figure out that if the variable name is the same as the dimension name, the coordinates attribute will not include that"coordinate".  For example, in Example 4,
variable float band(band)
So the coordinates of the variable swath_data(time,scan,band)
is "lon lat" instead of "lon lat band".

This is perfectly fine but we need to add a paragraph to explicitly explain this rule.

**Comment by ghost** [comment]
This proposal will hopefully be part of the CF convention so we don't have to provide explanation for every CF feature. At a later stage of final editing we may insert cross-references when mentioning them for the first some.
