### ISSUE TITLE
Comments: Misc minor issues

### ISSUE THREAD

**Issue by kyang2014** [ajelenak-thg/EC-netCDF-CF#3]
1. For example 5: Multiband data with string spectral coordinate.

Add (netCDF extended model)

2.  The abbreviation of Field of Regard is FOR. However, "for" is widely used in the programming language. Can we change it to "fore" or something else?

**Comment by ghost** [comment]
> For example 5: Multiband data with string spectral coordinate.
> Add (netCDF extended model)

Where? To that example's text? Make it: _Multiband data with string spectral coordinate **(for netCDF extended data model)**_

> The abbreviation of Field of Regard is FOR. However, "for" is widely used in the programming language. Can we change it to "fore" or something else?

I noticed that too but not sure that in this context it can be easily confused with `for` loops. _fore_ means _forward_ and is a well-known term in scatterometry for antenna position with regard to the satellite motion. Perhaps we could go all caps? `FOR` and `FOV`?

**Comment by dasantek** [comment]
I did all caps. See what you think.
