### ISSUE TITLE
Declare "for" a coordinate in the Multiband Field-of-Regard with Field-of-View Shapes example

### ISSUE THREAD

**Issue by ghost** [ajelenak-thg/EC-netCDF-CF#5]
In the "FOR" examples, should the "for" dimension become a coordinate variable, similar to what is done with "fov"?

**Comment by kyang2014** [comment]
No strong opinion. Seems OK to treat it as fov.

**Comment by ghost** [comment]
Thanks! Closing this issue since we merged Dave's branch this morning where these names were all uppercase.
