### ISSUE TITLE
Need a Swath Coordinate section?

### ISSUE THREAD

**Issue by ghost** [ajelenak-thg/EC-netCDF-CF#9]
This would discuss unique aspects of pixel location: geodetic or geocentric (planetodetic, planetocentric for other planetary bodies), a fill value (when the swath is off-planet), XYZ (instead of lat/lon)? Even if we aren't going to include these specifications in the initial recommendation, I think the issues should be noted.

**Comment by dasantek** [comment]
Added text to swath document to address this issue. It is not complete and the example is from MODIS, rather than an generic specification. We need to discuss.
